---
version: "3.8"
services:
  sfn:
    image: amazon/aws-stepfunctions-local
    ports:
      - "8083:8083"
    env_file:
      - .env

  moto:
    image: motoserver/moto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # - "4566:4566"
      - "5555:5000"
